apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "resource-name" . }}
  labels:
    {{- include "labels" . | indent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`localhost`) && PathPrefix(`/{{ include "resource-name" . }}/`)
      middlewares:
        - name: {{ include "resource-name" . }}
      services:
        - kind: Service
          name: {{ include "resource-name" . }}
          port: {{ include "app-name" . }}
