apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namePrefix: prod-
labels:
  - pairs:
      env: prod
    includeSelectors: true
replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 2
patches:
  - target:
      kind: HelmRelease
      name: backend
    patch: |-
      - op: add
        path: /spec/values
        value:
          env: prod
          app: backend
  - target:
      kind: HelmRelease
      name: frontend
    patch: |-
      - op: add
        path: /spec/values
        value:
          env: prod
          app: frontend
  - target:
      kind: ConfigMap
      name: frontend
    patch: |-
      - op: replace
        path: /data/config.json
        value: '{"api":"http://localhost:8080/prod-backend"}'
