apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: prod-
labels:
  - pairs:
      env: prod
    includeSelectors: true
replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 2
patches:
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
