apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./middleware.yaml
  - ./service.yaml
  - ./route.yaml
  - ./deployment.yaml
generators:
  - configmap.yaml
labels:
  - pairs:
      app: frontend
    includeSelectors: true
