apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend
spec:
  interval: 10m
  chart:
    spec:
      interval: 10m
      chart: ./gitops/charts/external-service
      version: "1.x.x"
      sourceRef:
        kind: GitRepository
        namespace: flux-system
        name: fleet-infra
