apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fleet-infra
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/SadraSamadi/fleet-infra
  ref:
    branch: main
  ignore: |
    /*
    !/gitops/charts/
