apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
generators:
  - configmap.yaml
labels:
  - pairs:
      app: frontend
    includeSelectors: true
