apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 10m
  chart:
    spec:
      interval: 1h
      chart: minio
      version: "16.*.*"
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bitnami
