apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: shuttle
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/SadraSamadi/fleet-infra
  ref:
    branch: shared
  ignore: |
    /*
    !/gitops/charts/
