apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namePrefix: stage-
labels:
  - pairs:
      env: stage
    includeSelectors: true
patches:
  - target:
      kind: HelmRelease
      name: backend
    patch: |-
      - op: add
        path: /spec/values
        value:
          env: stage
          app: backend
  - target:
      kind: HelmRelease
      name: frontend
    patch: |-
      - op: add
        path: /spec/values
        value:
          env: stage
          app: frontend
  - target:
      kind: ConfigMap
      name: frontend
    patch: |-
      - op: replace
        path: /data/config.json
        value: '{"api":"http://localhost:8080/stage-backend"}'
