apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namePrefix: stage-
labels:
  - pairs:
      env: stage
    includeSelectors: true
patches:
  - target:
      kind: Middleware
      name: backend
    patch: |-
      - op: replace
        path: /spec/stripPrefix/prefixes/0
        value: /stage-backend
  - target:
      kind: IngressRoute
      name: backend
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`localhost`) && PathPrefix(`/stage-backend/`)
      - op: replace
        path: /spec/routes/0/middlewares/0/name
        value: stage-backend
      - op: replace
        path: /spec/routes/0/services/0/name
        value: stage-backend
  - target:
      kind: Middleware
      name: frontend
    patch: |-
      - op: replace
        path: /spec/stripPrefix/prefixes/0
        value: /stage-frontend
  - target:
      kind: IngressRoute
      name: frontend
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`localhost`) && PathPrefix(`/stage-frontend/`)
      - op: replace
        path: /spec/routes/0/middlewares/0/name
        value: stage-frontend
      - op: replace
        path: /spec/routes/0/services/0/name
        value: stage-frontend
